### ISSUE TITLE
Clarify RH heights

### ISSUE THREAD

**Issue by rfbrown** [mcmlter/MDV-ClimEx#1]
- App pulls air temperature heights from EDI entity column names. 
- RH is sometimes measured at multiple heights.

**Comment by gavin-wagner** [comment]
RH is measured at each met station as follows:

### **Table of Relative Humidity Variables**

| Station | Height Measured | EDI Column Name |
|---------|-----------------|-------------|
CAAM | 1m | rh1m
CAAM | 2m | rh2m
CAAM | 3m | rh3m
CAHM | 3m | rh
EXEM | Unspecified | rh
FRSM | 3m | rh
HODM | Unspecified | rh
BOYM | 3m | rh
BRHM | 3m | rh
FRLM | Unspecified | rh
HOEM | Unspecified | rh
VAAM | 3m | rh
VIAM | 3m | rh
MISM | 3m | rh
FLMM | 3m | rh
TARM | 3m | rh
TARM | 1m | rh1m

**Comment by gavin-wagner** [comment]
Currently, variables with the column name "rh" are labeled "Relative Humidity (%)." If a height is specified in the column name, a height is included in the label.

Is it safe to assume that the unspecified ones are at 3m? In that case, I can adjust the label across the board

**Comment by rfbrown** [comment]
Updating the table for the record. 

RH is measured at each met station as follows:

### **Table of Relative Humidity Variables**

| Station | Height Measured | EDI Column Name | Remarks
|---------|-----------------|-------------|-------------|
BOYM | 3m | rh | confirmed
BRHM | 3m | rh | confirmed
CAAM | 1m | rh1m | confirmed
CAAM | 2m | rh2m | confirmed
CAAM | 3m | rh3m | confirmed
COHM | 3m | rh | confirmed
EXEM | 3m | rh | confirmed
FLMM | 3m | rh | confirmed; however, airt is mislabeled in EDI as 2m and should be 3m
FRLM | 3m | rh | confirmed
FRSM | 3m | rh | confirmed
HODM | 1m | rh1m | added to table and confirmed (both heights already in app)
HODM | 3m | rh | confirmed
HOEM | 3m | rh | confirmed
MISM | 3m | rh | confirmed
TARM | 1m | rh1m | confirmed
TARM | 3m | rh | confirmed
VAAM | 3m | rh | confirmed
VIAM | 3m | rh | confirmed

**Comment by gavin-wagner** [comment]
Added "at 3m" to the laynames for Relative Humidity which correspond to a variable name of "rh" (Lines 256 and 274). Data listed as such in EDI is recorded at 3m even though it is unspecified. An extra space is added between "at" and "3m" because there is already a "Relative humidity at 3m" layname entry to correspond to the "rh3m" variable name.
