### ISSUE TITLE
Bug in parameter selection when new met station is selected

### ISSUE THREAD

**Issue by rfbrown** [mcmlter/MDV-ClimEx#9]
In app.R, add code in section "# Update choices when a new met station is selected" to address a bug that occurs when a user has selected a particular parameter suite, e.g., EXEM RADN, then selects a new station that does not have this parameter suite, e.g., FRSM. When this occurs, the app crashes with the following error: `Warning: Error in : '../data/FRSM/FRSM_RADN/FRSM_RADN.csv' does not exist in current working directory...`

**Comment by gavin-wagner** [comment]
Added code in section "# Update choices when a new met station is selected" to include a req() checkpoint before the app pulls the parameter suite data for the chosen met station. The req() checkpoint checks the existence of the file path to the chosen met/parameter combination, which ensures that the app has had enough time to repopulate the set of available parameter suites with those from the chosen met.
